#!/bin/sh
temp_folder=$HOME/.config/hypr/scripts/variables/temp

hypr=$HOME/.config/hypr
wallpaper_folder=$(head -1 $temp_folder/folder)

wallpaper_location="$(ls $wallpaper_folder | wofi --show dmenu -k "/dev/null")"

echo "$wallpaper_folder/$wallpaper_location"

if [[ -d $wallpaper_folder/$wallpaper_location ]]; then
    echo "$wallpaper_folder/$wallpaper_location is a directory"
    wallpaper_temp="$wallpaper_location"
    sleep2
elif [[ -f $wallpaper_folder/$wallpaper_location ]]; then
    echo "$wallpaper_folder/$wallpaper_location is a file"
else
    echo "$wallpaper_folder/$wallpaper_location is not valid"
    exit 1
fi


echo "$wallpaper_folder/$wallpaper_temp/$wallpaper_location"

$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_temp$wallpaper_location"

$hypr/scripts/wallpaper
