#!/usr/bin/env bash

# Directory
hypr_dir="$HOME/.config/hypr/themes"
waybar_dir="$HOME/.config/waybar/themes"
kitty_dir="$HOME/.config/kitty/themes"
wallpaper_dir="$HOME/Pictures/wallpapers"
discord="$HOME/.var/app/com.discordapp.Discord/config/BetterDiscord/themes"
discord_dest="$HOME/.var/app/com.discordapp.Discord/config/BetterDiscord/data/stable"

prompt="wofi --show dmenu -k "/dev/null" -always_parse_args=true"

# theme
cancel="窱 Cancel"
theme1=" Dracula"
theme2=" Black"
theme3=" White"

# Variable to pass to dmenu or rofi
option="$cancel\n$theme1\n$theme2\n$theme3"

select="$(echo -e "$option" | $prompt -p "Choose a theme: " )"

change_theme()
{
  cp ${hypr_dir}/$1.conf ${hypr_dir}/color.conf
  cp ${waybar_dir}/$1.css ${waybar_dir}/color.css
  cp ${kitty_dir}/$1.conf ${kitty_dir}/color.conf
  cp ${discord}/$1.theme.css ${discord_dest}/custom.css
  rm -r $HOME/.config/spicetify/Themes/color/
  cp -r $HOME/.config/spicetify/Themes/$1 $HOME/.config/spicetify/Themes/color
}

case $select in
  $theme1)
    change_theme dracula
    hyprctl reload
    killall -s SIGUSR1 kitty
    killall waybar
    waybar -c $HOME/.config/waybar/config -s $HOME/.config/waybar/style.css > /dev/null &
    echo ${wallpaper_dir}/catppuccin > $HOME/.config/hypr/scripts/variables/temp/folder
    ;;
  $theme2)
    change_theme black
    hyprctl reload
    killall -s SIGUSR1 kitty
    killall waybar
    waybar -c $HOME/.config/waybar/config -s $HOME/.config/waybar/style.css > /dev/null &
    echo ${wallpaper_dir}/blackandwhite > $HOME/.config/hypr/scripts/variables/temp/folder
    ;;
  $theme3)
    change_theme white
    hyprctl reload
    killall -s SIGUSR1 kitty
    killall waybar
    waybar -c $HOME/.config/waybar/config -s $HOME/.config/waybar/style.css > /dev/null &
    echo ${wallpaper_dir}/blackandwhite > $HOME/.config/hypr/scripts/variables/temp/folder
    ;;
  esac

kitty -e spicetify apply
